twig:
  default_path: "%kernel.project_dir%/templates"
  form_themes:
    - bootstrap_4_layout.html.twig
  globals:
    categoryRepsository: "@App\\Repository\\CategoryRepository"

when@test:
  twig:
    strict_variables: true
